- id: doi:org/10.21203/rs.3.rs-1510675/v1
  image:
  date: 2022-4-28
- id: doi:10.3389/fnins.2022.922960
  image:
  date: 2022-8-14
  
- id: doi:10.1111/ejn.14542
  image:
  date: 2019-4-3
- id: doi:10.1016/j.csbj.2020.05.017
  image:
  date: 2020-6-2
  extra-links:
    - type: manubot
      link: https://greenelab.github.io/knowledge-graph-review/
  tags:
    - knowledge graphs

- id: doi:10.1371/journal.pcbi.1007128
  repo: greenelab/meta-review
  extra-links:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/

- id: doi:10.7554/eLife.32822
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
  extra-links:
    - type: preprint
      link: https://doi.org/10.7287/peerj.preprints.3100v1
    - type: manubot
      link: https://greenelab.github.io/scihub-manuscript/
    - type: source
      link: https://github.com/greenelab/scihub-manuscript
      text: Manuscript source
    - type: source
      link: https://github.com/greenelab/scihub
      text: Analyses source

- id: doi:10.1364/josaa.14.000013
  image:
  date: 
  
- id: doi:10.1016/s0042-6989(97)00294-0
  image:
  date: 
  
- id: doi:10.1155/2014/301473
  image:
  date:
  
- id: doi:10.1023/a:1010499119393
  image:
  date:
  
- id: doi:10.1038/nn775
  image:
  date:
  
- id: doi:10.1016/j.cogbrainres.2003.10.014
  image:
  date:
  
- id: d1oi:10.1016/j.neuroimage.2006.09.007
  image:
  date:
  
- id: doi:10.1093/cercor/bhm248
  image:
  date:
  
- id: doi:10.1073/pnas.0809609106
  image:
  date:
  
- id: doi:10.1016/j.neuroimage.2010.03.055
  image:
  date:

- id: doi:10.1073/pnas.1003174107
  image:
  date:
  
- id: doi:10.1097/AUD.0b013e3181ec5d7a
  image:
  date:
  
- id: doi:10.1016/j.brainres.2010.12.022
  image:
  date:
  
- id: doi:10.36510/learnland.v5i1.542
  image:
  date:
  
- id: doi:10.1162/jocn_a_00143
  image:
  date:
  
- id: doi:10.3758/s13428-012-0273-2
  image:
  date:
  
- id: doi:10.1016/j.bandl.2012.06.005
  image:
  date:
  
- id: doi:10.1002/hbm.22024
  image:
  date:
  
- id: doi:10.3109/14992027.2012.743044
  image:
  date: 
  
- id: doi:10.1016/j.bandl.2012.11.009
  image:
  date:   
  
- id: doi:10.1371/journal.pone.0058130
  image:
  date:   
 
- id: doi:10.1186/1471-244X-13-264
  image:
  date: 
 
- id: doi:10.1016/j.neuroimage.2013.09.026
  image:
  date: 
  
- id: doi:10.1016/j.bandc.2014.01.013
  image:
  date: 

- id: doi:10.1111/psyp.12299
  image:
  date: 
  
- id: doi:10.1073/pnas.1510527112
  image:
  date: 

- id: doi:10.1007/s10548-015-0457-z
  image:
  date: 

- id: doi:10.1075/ml.11.1.06tre
  image:
  date: 

- id: doi: 10.1044/2016_AJA-15-0080
  image:
  date: 

- id: doi: 10.1089/brain.2016.0451
  image:
  date: 

- id: doi: 10.3758/s13415-017-0499-7
  image:
  date: 

- id: doi: 10.1111/apa.13839
  image:
  date: 

- id: doi: 10.1109/TLT.2017.2762688
  image:
  date: 

- id: doi: 10.1080/02699052.2018.1429022
  image:
  date: 

- id: doi: 10.1007/978-3-030-01087-4_19
  image:
  date: 

- id: doi: 10.1007/978-3-030-01087-4_5
  image:
  date: 

- id: doi: 10.1089/brain.2018.0611.
  image:
  date: 

- id: doi: 10.1007/978-3-030-28144-1_32
  image:
  date: 

- id: doi: 10.1177/0269881119872205
  image:
  date: 

- id: doi: 10.1111/ejn.14542.
  image:
  date: 

- id: doi: 10.1007/978-3-030-60073-0_17
  image:
  date: 

- id: doi: 10.1007/978-3-030-60073-0_34
  image:
  date: 

- id: doi: 10.1371/journal.pone.0236800
  image:
  date: 

- id: doi: 10.1016/j.earlhumdev.2021.105308
  image:
  date: 

- id: doi: 10.1016/j.earlhumdev.2021.105363
  image:
  date: 

- id: doi: 10.1016/j.bandc.2021.105757
  image:
  date: 

- id:  doi: 10.3389/fnhum.2021.697532
  image:
  date: 

- id: doi: 10.3389/fpsyg.2022.668276
  image:
  date: 

- id: doi: 10.3389/fnins.2022.922960
  image:
  date: 
